// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ6FSNR2Xh_InhS1Uol9VZsrtKfEcWGck',
    appId: '1:236060093733:web:547022ce72628dffe43ecc',
    messagingSenderId: '236060093733',
    projectId: 'simplfi-b126b',
    authDomain: 'simplfi-b126b.firebaseapp.com',
    storageBucket: 'simplfi-b126b.appspot.com',
    measurementId: 'G-1LHV4D8PLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqNPyBnGC5QuKO6wN-cPcGbJbOAZuwGbo',
    appId: '1:236060093733:android:f87430652d94af49e43ecc',
    messagingSenderId: '236060093733',
    projectId: 'simplfi-b126b',
    storageBucket: 'simplfi-b126b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCstXQay0NBkt922QNSEzcTdALh0nOdr4E',
    appId: '1:236060093733:ios:455f318f24a56806e43ecc',
    messagingSenderId: '236060093733',
    projectId: 'simplfi-b126b',
    storageBucket: 'simplfi-b126b.appspot.com',
    iosClientId: '236060093733-tj44glokn14l0kk50g64krskbqskrdh8.apps.googleusercontent.com',
    iosBundleId: 'zenifinn.simplfi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCstXQay0NBkt922QNSEzcTdALh0nOdr4E',
    appId: '1:236060093733:ios:455f318f24a56806e43ecc',
    messagingSenderId: '236060093733',
    projectId: 'simplfi-b126b',
    storageBucket: 'simplfi-b126b.appspot.com',
    iosClientId: '236060093733-tj44glokn14l0kk50g64krskbqskrdh8.apps.googleusercontent.com',
    iosBundleId: 'zenifinn.simplfi',
  );
}
